version: "3.8"
services:
  db:
    container_name: db_govinchik
    image: postgres:16.4-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - dbgovinchik:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
      
volumes:
  dbgovinchik:
      